### PR TITLE
194 bug display default user icon for the owner of a shared configuration when the user does not have an icon

### LINKED ISSUE #194: [BUG] Display default user icon for the owner of a shared configuration when the user does not have an icon

### PR DESCRIPTION
**Pull request by Elkrival**
Expanded config icon avatar condition and added uid property to be returned in query.
Screen Shot 2022-10-05 at 8 39 19 AM

### CODE REVIEW

File: views/components/Config/ConfigCardAvatar.jsx [hunk 1]
```diff
@@ -0,0 +1,38 @@
+import React from 'react'
+import Avatar from '@material-ui/core/Avatar'
+
+import { colors } from '../../../constants'
+
+const ConfigCardAvatar = ({ ownsConfig, configOwner, userAvatar }) => {
+  if (ownsConfig) return userAvatar
+  if (!ownsConfig) {
```
Comment (mikestone14) [inline views/components/Config/ConfigCardAvatar.jsx]: based on the condition above this will always be true, right? Do we ever get to the `else` here?

File: babel.config.js [hunk 2]
```diff
@@ -0,0 +1,6 @@
+module.exports = {
```
Comment (mikestone14) [inline babel.config.js]: why do we need this change?

File: views/components/Config/ConfigCardAvatar.jsx (hunk 1 above)
Comment (Elkrival) [reply views/components/Config/ConfigCardAvatar.jsx]: There's a check for who owns the config. 
https://github.com/AMP-SCZ/dpdash/blob/04f0a2ef6096e2c5215a6ec69957542b0e245126/views/Config.react.js#L472-L473

and the second part is when I looked at the response it's a mixed bag of empty brackets or empty string.

Screen Shot 2022-10-05 at 9 38 12 AM
Screen Shot 2022-10-05 at 9 38 18 AM

File: babel.config.js (hunk 2 above)
Comment (Elkrival) [reply babel.config.js]: https://github.com/AMP-SCZ/dpdash/pull/196/commits/e0bd6fb1e11424a7015ce298c8142d6bdb322bd0

Comment (mikestone14) [reply babel.config.js]: I see it was removed but I'm still curious why it was added. Do we need this? What did it solve?

File: views/components/Config/ConfigCardAvatar.jsx (hunk 1 above)
Comment (mikestone14) [reply views/components/Config/ConfigCardAvatar.jsx]: I don't think we're talking about the same thing. On line 7 we're explicitly returning `userAvatar` if `ownsConfig` is `true`. Therefore, we shouldn't need to check if `ownsConfig` is `false` here.

File: babel.config.js (hunk 2 above)
Comment (Elkrival) [reply babel.config.js]: We will need this for testing, I probably clicked something and it added it to the commit, going forward i'll make sure that files outside of scope of a ticket are not part of the pr.

File: views/components/Config/ConfigCardAvatar.jsx (hunk 1 above)
Comment (Elkrival) [reply views/components/Config/ConfigCardAvatar.jsx]: https://github.com/AMP-SCZ/dpdash/pull/196/commits/df2c5afaba791766d6e380f325926726774163d4

File: views/components/Config/ConfigCardAvatar.jsx [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+            backgroundColor: colors.columbia_blue,
+          }}
+        >
+          {uid[0]}
+        </Avatar>
+      )
+    }
+  } else {
+    return userAvatar
+  }
```
Comment (mikestone14) [inline views/components/Config/ConfigCardAvatar.jsx]: this looks good but I think we can simplify the logic slightly for readability. What do you think about the below suggestion?
```suggestion
  if (!!ownsConfig) {
    return userAvatar
  }

  const { icon, uid } = configOwner
  
  return !!icon
   ? <Avatar src={icon} alt="" style={AVATAR_STYLE} />
   : <Avatar style={AVATAR_STYLE}>{uid[0]}</Avatar>
```

File: views/components/Config/ConfigCardAvatar.jsx [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+import { colors } from '../../../constants'
+
+const ConfigCardAvatar = ({ ownsConfig, configOwner, userAvatar }) => {
+  if (!ownsConfig) {
+    const { icon, uid } = configOwner
+    if (!!icon) {
+      return (
+        <Avatar
+          src={icon}
+          alt=""
```
Comment (mikestone14) [inline views/components/Config/ConfigCardAvatar.jsx]: should we add alt text?

File: views/Config.react.js [hunk 5]
```diff
@@ -487,15 +489,11 @@ class ConfigPage extends Component {
...
-                    alt=""
-                    className={this.props.classes.configIcon}
-                  />
-                ) : (
-                  this.state.avatar
-                )
+                <ConfigCardAvatar
+                  ownsConfig={ownsConfig}
+                  configOwner={configs[item]?.configOwner}
+                  userAvatar={this.state.avatar}
```
Comment (mikestone14) [inline views/Config.react.js]: if the `configOwner` has the same attributes as a `user` I think we could make this a little simpler and do something like:

```js
<ConfigCardAvatar config={configs[item]} currentUser={user} />
```

and then in the `ConfigCardAvatar` component...

```jsx
const ConfigCardAvatar = (props) => {
  const isCurrentUserConfig = props.user.id === props.config.owner
  const avatarUser = isCurrentUserConfig ? props.user : props.config.configOwner

  return getAvatar({ user: avatarUser })
}
```

File: server/routes/index.js [hunk 6]
```diff
@@ -767,14 +767,15 @@ router
               {
                 $project: {
                   icon: 1,
+                  uid: 1,
                   _id: 0,
                 },
               },
             ],
-            as: 'icon',
+            as: 'configOwner',
```
Comment (mikestone14) [inline server/routes/index.js]: since this is already a `config` object I wonder if we can remove that from the name (since it is implied) and have a more descriptive name for this attribute like `ownerUser` if this is going to be a user object.

Comment (Elkrival) [reply server/routes/index.js]: https://github.com/AMP-SCZ/dpdash/pull/196/commits/159c5b43ba6f258f9ca42cfd988c9f29017e7d09

File: views/Config.react.js (hunk 5 above)
Comment (Elkrival) [reply views/Config.react.js]: https://github.com/AMP-SCZ/dpdash/pull/196/commits/159c5b43ba6f258f9ca42cfd988c9f29017e7d09

File: views/components/Config/ConfigCardAvatar.jsx (hunk 3 above)
Comment (Elkrival) [reply views/components/Config/ConfigCardAvatar.jsx]: https://github.com/AMP-SCZ/dpdash/pull/196/commits/159c5b43ba6f258f9ca42cfd988c9f29017e7d09

File: views/components/Config/ConfigCardAvatar.jsx (hunk 4 above)
Comment (Elkrival) [reply views/components/Config/ConfigCardAvatar.jsx]: https://github.com/AMP-SCZ/dpdash/pull/196/commits/159c5b43ba6f258f9ca42cfd988c9f29017e7d09

File: constants/styles.js [hunk 7]
```diff
@@ -30,3 +31,10 @@ export const presetColors = [
   colors.deep_green,
   colors.smokey_topaz,
 ]
+
+export const DEFAULT_AVATAR_STYLE = { width: 60, height: 60 }
+
+export const AVATAR_STYLE_WITH_COLOR = {
+  ...DEFAULT_AVATAR_STYLE,
+  backgroundColor: colors.columbia_blue,
+}
```
Comment (mikestone14) [inline constants/styles.js]: I don't think we need these in a global area. They can just live in the `UserAvatar` component since they are unlikely to be shared outside of the avatar.

**Review by mikestone14 — APPROVED** [review]
Looks good just one minor comment.

File: views/components/Config/ConfigCardAvatar.jsx [hunk 8]
```diff
@@ -0,0 +1,13 @@
+import React from 'react'
+
+import UserAvatar from '../UserAvatar'
+
+const ConfigCardAvatar = (props) => {
+  const isCurrentUserConfig = props.currentUser.uid === props.config.ownerUser
```
Comment (mikestone14) [inline views/components/Config/ConfigCardAvatar.jsx]: is `ownerUser` an object? Do we need `ownerUser.uid` here?

Comment (Elkrival) [reply views/components/Config/ConfigCardAvatar.jsx]: yes good catch https://github.com/AMP-SCZ/dpdash/pull/196/commits/f307adf2b8668c103503147fc268b63c299b99c6

File: constants/styles.js (hunk 7 above)
Comment (Elkrival) [reply constants/styles.js]: https://github.com/AMP-SCZ/dpdash/pull/196/commits/f307adf2b8668c103503147fc268b63c299b99c6
