### PR TITLE
180 fix the importer script

### LINKED ISSUE #180: Fix the importer script
There is an error during the cron job that is looking for an importer.js file in the wrong path.

Image

### PR DESCRIPTION
**Pull request by Elkrival**
There is an error when the cron job runs, it is looking for a script in the wrong path. This pr checks if the file exists and runs the script, should stop from crashing the app. The first commit is all formatting, the diff for the actual change is here.
https://github.com/AMP-SCZ/dpdash/commit/639476792a747227fabf1e187c021a823717f9c4

Screenshot of error.
Screen Shot 2022-09-21 at 11 08 13 AM

Link to slack channel discussion 
https://gnardog.slack.com/archives/C03KGHSSTNC/p1661442139221189?thread_ts=1661442042.834439&cid=C03KGHSSTNC

### CODE REVIEW

File: server/bin/www.js [hunk 1]
```diff
@@ -113,26 +115,31 @@ for (const hour in config.rabbitmq.sync.hours) {
...
-        console.log(`child process exited with code ${code}`)
-      })
-    },
-    start: true,
-    timeZone: config.rabbitmq.sync.timezone,
-  })
+
+  const importerPath = path.join(__dirname, '..', 'utils', 'importer.js')
+
+  if (fs.existsSync(importerPath)) {
```
Comment (tashrifbillah) [inline server/bin/www.js:121]: Hi @Elkrival , I see that you have only added this `if` condition. Does this assure that the issue won't happen?

Comment (Elkrival) [reply server/bin/www.js:121]: Yes, this checks the existence of the importer.js file, if the file exists then we run the work from the file.

**Review by tashrifbillah — APPROVED** [review]
