### PR TITLE
306 Fix account expires bug

### LINKED ISSUE #306: Fix the user account expires bug
User's are not able to log in. Setting the account expires date is not allowing access.

### PR DESCRIPTION
**Pull request by Elkrival**
closes #306 

The bug includes an issue that after logout a user can still have access to the application. This is because the cookie and session were not being removed properly.

### CODE REVIEW

File: views/api/auth/index.js [hunk 1]
```diff
@@ -12,6 +12,13 @@ const auth = {
 
     return handleApiResponse(response)
   },
+  logout: async () => {
+    const response = await fetch(apiRoutes.auth.logout, {
+      ...BASE_REQUEST_OPTIONS,
+    })
```
Comment (mikestone14) [inline views/api/auth/index.js]:
```suggestion
    const response = await fetch(apiRoutes.auth.logout, BASE_REQUEST_OPTIONS)
```

File: views/components/Sidebar.jsx [hunk 2]
```diff
@@ -14,8 +18,20 @@ const Sidebar = ({
...
+  const navigate = useNavigate()
+
+  const handleLogout = async () => {
+    try {
+      await api.auth.logout()
+
+      setUser(null)
+      navigate(routes.login)
+    } catch (error) {
+      throw new Error(error)
```
Comment (mikestone14) [inline views/components/Sidebar.jsx]: We are catching the error and then throwing a new error wrapping the error. This is almost the same as not catching at all, except not we have an error in an error being thrown. Let's either catch the error and handle it or not catch it at all.

```suggestion
      alert(error.message)
```

File: views/routes/routes.js [hunk 3]
```diff
@@ -16,7 +16,7 @@ export const routes = {
   charts: `${basePath}/charts`,
   reports: `${basePath}/reports`,
   admin: `${basePath}/admin`,
-  login: `${basePath}/login`,
+  login: `/login`,
```
Comment (mikestone14) [inline views/routes/routes.js:19]: why are we removing the basePath here but nowhere else?

**Review by mikestone14 — COMMENTED** [review]
This looks great, just a couple minor things.

File: views/routes/routes.js (hunk 3 above)
Comment (Elkrival) [reply views/routes/routes.js:19]: Those changes belong to this pr. https://github.com/AMP-SCZ/dpdash/pull/319

File: views/components/Sidebar.jsx (hunk 2 above)
Comment (Elkrival) [reply views/components/Sidebar.jsx]: [fd6e0cb](https://github.com/AMP-SCZ/dpdash/pull/323/commits/fd6e0cbe82ffb8f78b65b8841e1d9e4dd676d278)

File: views/api/auth/index.js (hunk 1 above)
Comment (Elkrival) [reply views/api/auth/index.js]: [fd6e0cb](https://github.com/AMP-SCZ/dpdash/pull/323/commits/fd6e0cbe82ffb8f78b65b8841e1d9e4dd676d278)

File: views/routes/routes.js (hunk 3 above)
Comment (mikestone14) [reply views/routes/routes.js:19]: I'm not sure I follow. So you're saying this diff shouldn't be in this PR and is going to be removed?

Comment (Elkrival) [reply views/routes/routes.js:19]: To separate the account_expires work and other pieces of work the basePath is removed in pr #319  for the other routes.

Comment (mikestone14) [reply views/routes/routes.js:19]: ok let's move this diff over to #319 then so this PR is isolated to the account expires bug.

Comment (Elkrival) [reply views/routes/routes.js:19]: I feel like this goes together after logout we reroute to login. The other diff includes the other pages because that's what that pr is focused around

Comment (mikestone14) [reply views/routes/routes.js:19]: right, but that path already exists. Are you saying the path needs to change in order for this to work? I think the base path is empty anyway so this doesn't break/fix the path.

Comment (Elkrival) [reply views/routes/routes.js:19]: Yes I feel like this will break in a deployed instance, as the application is being deployed the basePath file is being written on the fly and I don't know what those values could be. To avoid the risk of it not working it is best to remove it.  https://github.com/AMP-SCZ/dpdash/blob/bf46996b5d49c8e60584c290779f1752a942061c/singularity/configure.py#L416-L424

**Review by mikestone14 — APPROVED** [review]
