### PR TITLE
Fix bar graph exceeding 100%

### LINKED ISSUE #197: [BUG] When percentages exceed 100%, the N/A group has a negative value & percent

### PR DESCRIPTION
**Pull request by Elkrival**
When a bar in the graph exceeds 100% the NA section has a negative percentage. We default the value to zero.

Screen Shot 2022-10-06 at 1 27 14 PM
In the above screenshot one value exceeds 225% but the negative N/A percentage displays it as 180%

Screen Shot 2022-10-06 at 1 30 09 PM
Defaulting to zero in these cases represents the bar section completely

### CODE REVIEW

File: server/controllers/chartsController.js [hunk 1]
```diff
@@ -60,10 +60,11 @@ const postProcessData = (data, studyTotals) => {
...
       ? studySectionTotals.targetTotal - studySectionTotals.count
       : 0
-    const percent = studyCountsToPercentage(
-      count,
-      studySectionTotals.targetTotal ?? studySectionTotals.count
-    )
+    const studySectionTargetValue =
+      studySectionTotals.targetTotal > studySectionTotals.count
+        ? studySectionTotals.targetTotal
+        : 0
```
Comment (mikestone14) [inline server/controllers/chartsController.js]: Don't we also want to keep the logic here that we should use the count if we don't have a target total?

Comment (Elkrival) [reply server/controllers/chartsController.js]: https://github.com/AMP-SCZ/dpdash/pull/198/commits/e9480622bafa814cb0d48340a648e9c763dac837

File: server/controllers/chartsController.js [hunk 2]
```diff
@@ -194,3 +195,13 @@ export const graphDataController = async (dataDb, userAccess, chart_id) => {
...
 }
+
+function calculateStudySectionTargetValue(
+  studySectionTotalTarget,
+  studySectionTotalCount
+) {
+  if (studySectionTotalTarget > studySectionTotalCount)
+    return studySectionTotalTarget
+  if (!studySectionTotalTarget) return studySectionTotalCount
+  return 0
```
Comment (mikestone14) [inline server/controllers/chartsController.js]: This is a nit but I think it'll be more readable to have the guard clause first. Also, I think we want to return the `studySectionTotalCount` if we don't have a `studySectionTotalTarget`. Does that sound right to you?

```suggestion
  if (!studySectionTotalTarget) return studySectionTotalCount

  if (studySectionTotalTarget > studySectionTotalCount)
    return studySectionTotalTarget
  
  return studySectionTotalCount || 0
```

Comment (Elkrival) [reply server/controllers/chartsController.js]: yes that sounds right to me.

What do you think about this line `return studySectionTotalCount || 0` becoming this line `return studySectionTotalCount` otherwise I don't know when we would default to 0

Comment (mikestone14) [reply server/controllers/chartsController.js]: ok as long as we will always have a `studySectionTotalCount` then that will work.

Comment (Elkrival) [reply server/controllers/chartsController.js]: https://github.com/AMP-SCZ/dpdash/pull/198/commits/d2d0b6fef4ed39c1fe5c13ec2e99b126130b8482

File: server/controllers/chartsController.js [hunk 3]
```diff
@@ -56,14 +56,15 @@ const postProcessData = (data, studyTotals) => {
...
-    const studySectionTotals = studyTotals[study]
-    const count = studySectionTotals.targetTotal
-      ? studySectionTotals.targetTotal - studySectionTotals.count
-      : 0
-    const percent = studyCountsToPercentage(
-      count,
-      studySectionTotals.targetTotal ?? studySectionTotals.count
+    const { targetTotal, count: currentSiteCount } =
+      studyTotals[study].studySectionTotals
+    const isTargetPositive = targetTotal && targetTotal > currentSiteCount
```
Comment (mikestone14) [inline server/controllers/chartsController.js]: this isn't determining if the target is positive but instead if it is greater than the count.

File: server/controllers/chartsController.js [hunk 4]
```diff
@@ -194,3 +195,14 @@ export const graphDataController = async (dataDb, userAccess, chart_id) => {
...
+
+function calculateStudySectionTargetValue(
+  studySectionTotalTarget,
+  studySectionTotalCount
+) {
+  if (!studySectionTotalTarget) return studySectionTotalCount
+  if (studySectionTotalTarget > studySectionTotalCount)
+    return studySectionTotalTarget
+
+  return studySectionTotalCount || 0
```
Comment (mikestone14) [inline server/controllers/chartsController.js]:
```suggestion
  if (!!studySectionTotalTarget && studySectionTotalTarget > studySectionTotalCount) {
    return studySectionTotalTarget
  }

  return studySectionTotalCount || 0
```

File: server/controllers/chartsController.js (hunk 3 above)
Comment (Elkrival) [reply server/controllers/chartsController.js]: haha, thank you for bringing that up. I was considering isTargetGreaterThanCount but it looks to long, what are your thoughts on a name?

Comment (mikestone14) [reply server/controllers/chartsController.js]: something that accurately describes what it is. `isTargetGreaterThanCount` is fine.

Comment (Elkrival) [reply server/controllers/chartsController.js]: https://github.com/AMP-SCZ/dpdash/pull/198/commits/d6e7fa70948aed4f4b988c2e1992e12fd48a0c4e

File: server/controllers/chartsController.js (hunk 4 above)
Comment (Elkrival) [reply server/controllers/chartsController.js]: https://github.com/AMP-SCZ/dpdash/pull/198/commits/d6e7fa70948aed4f4b988c2e1992e12fd48a0c4e

**Review by mikestone14 — APPROVED** [review]
