### PR TITLE
Fix crash from tooltip

### LINKED ISSUE #725: Bug loading charts
The new linting rules have reformatted pieces of the code that loads charts, and now they won't load. 

Refactor the code to follow linting rules and fix the following error.

Image

### PR DESCRIPTION
**Pull request by Elkrival**
closes #725 

This pr fixes an issue that happens when a user is hovering over the bar graph some bars may cause it to crash.
If you see in the video as I get further to the right, so does the tooltip and it passes the edge of bar graph, this change here
`const tooltipWidth = 235` places the tooltip a little more to the left.

[Video of bug fix Part I](https://drive.google.com/file/d/1utvjOz65jk0UocEB2bLCwg7ezLELFXQ5/view?usp=sharing)

### CODE REVIEW

File: views/components/BarGraphTooltip/index.jsx [hunk 1]
```diff
@@ -14,10 +14,10 @@ const BarGraphTooltip = ({
 }) => {
   if (!active || !payload?.length) return null
 
-  const siteName = useSiteName ? label : SITE_NAMES[label]
+  const siteName = useSiteName ? label : SITE_NAMES[label] || label
   const countsTotal = useSiteName
     ? studyTotals[label].count
-    : studyTotals[SITE_NAMES[label]].count
+    : studyTotals[SITE_NAMES[label] || label].count
```
Comment (mikestone14) [inline views/components/BarGraphTooltip/index.jsx]: can we use the `siteName` constant here?

```suggestion
    : studyTotals[siteName].count
```

Comment (mikestone14) [reply views/components/BarGraphTooltip/index.jsx]: Actually I think we can clean this up even further by changing

```js
  const countsTotal = useSiteName
    ? studyTotals[label].count
    : studyTotals[SITE_NAMES[label] || label].count
```

to

```js
  const countsTotal = studyTotals[siteName].count
```

Comment (Elkrival) [reply views/components/BarGraphTooltip/index.jsx]: The snippet looks good, and I want to get in your head, where is siteName coming from..?

Comment (Elkrival) [reply views/components/BarGraphTooltip/index.jsx]: Ah I see it at the top, thanks

Comment (Elkrival) [reply views/components/BarGraphTooltip/index.jsx]: [9dbeb38](https://github.com/AMP-SCZ/dpdash/pull/736/commits/9dbeb387aee249e8301096f872943cfa463512d0)

**Review by mikestone14 — APPROVED** [review]
