### PR TITLE
Scripts: Fix quit.sh, add renewssl.sh for renewing SSL certs

### LINKED ISSUE #23: In quit.sh, only kill related processes
Don't attempt to kill all `mongo` and `rabbitmq` processes, only the ones that are relevant to the instance.

### LINKED ISSUE #24: Add script to renew self-signed SSL certs
Right now they expire after a year, so they will need to be renewed annually.

### PR DESCRIPTION
**Pull request by blms**
Closes #23, closes #24.

### Changes
- Complete TODOs in `quit.sh`
  - Kill `pm2` with its built-in `kill` command
  - Send `SIGQUIT` to `supervisord` to shut down its children
  - Wait for `supervisord` to fully shut down
  - Print a colorful success message on completion
- Add `renewssl.sh` to renew self-signed SSL certs
  - Should be used when self-signed certificates expire, which happens every 365 days since generation
  - Revokes existing certs, then does [this part of `init.sh`](https://github.com/PREDICT-DPACC/dpdash/blob/585cb7cba46c2b3cd72432975340d8133dde47d6/singularity/init.sh#L51-L79) again
  - Since output filenames are identical, there is no need for any further action/configuration
  - Add [usage documentation to wiki](https://github.com/PREDICT-DPACC/dpdash/wiki/Renewing-self-signed-SSL-certificates)

### Testing
- [x] Tested both scripts myself
- [x] `renewssl.sh` was already used by Habib on their instance when certs expired
- [x] Rebuilt Singularity image: `/data/predict/dpdash-ben-0625.sif`

### CODE REVIEW

File: singularity/quit.sh [hunk 1]
```diff
@@ -7,14 +7,16 @@ set -eo pipefail
 cd /sw/apps/dpdash
 npm stop
 
-# TODO: make this do a graceful exit
+# kill PM2
+./node_modules/pm2/bin/pm2 kill
```
Comment (tashrifbillah) [inline singularity/quit.sh:11]: Sorry about the silly question--but is `node_modules/` in `/sw/apps/dpdash`?

Comment (blms) [reply singularity/quit.sh:11]: Yes, it is!

File: singularity/quit.sh [hunk 2]
```diff
@@ -7,14 +7,16 @@ set -eo pipefail
...
+kill -SIGQUIT $pid
 
-# TODO: send SIGQUIT to supervisord
-
-pkill -f 'supervisord'
-pkill -f 'rabbitmq'
-pkill -f 'erlang'
-pkill -f 'celery'
-pkill -f 'mongo'
+while kill -s 0 $pid ; do : ; sleep 0.25 ; done
```
Comment (tashrifbillah) [inline singularity/quit.sh:19]: So after every killing is done, are you waiting 0.25 seconds?

Comment (blms) [reply singularity/quit.sh:19]: I got this line from [this StackOverflow answer](https://askubuntu.com/a/1103089). In this line I'm just checking every 0.25 seconds if the process exists. That loop will go indefinitely until the process is successfully shutdown.

This is because `supervisord` takes a while to quit. It's indefinite how long that will take, so I just loop to check if it still exists until it's fully quit.

That way, when someone runs `run.sh`, they won't run into a conflict with `supervisord` not fully shutdown, and then get an error that the port is already used.

File: singularity/quit.sh [hunk 3]
```diff
@@ -7,14 +7,16 @@ set -eo pipefail
...
-pkill -f 'pm2'
+# kill supervisord (thus mongo, celery, erlang, rabbitmq)
+echo "Quitting supervisord..."
+pidfile="/data/dpdash/supervisord/supervisord.pid"
+pid=$(<$pidfile)
+kill -SIGQUIT $pid
 
-# TODO: send SIGQUIT to supervisord
-
-pkill -f 'supervisord'
```
Comment (tashrifbillah) [inline singularity/quit.sh:16]: Does `supervisord` killing ensure killing all supervised processes?

Comment (blms) [reply singularity/quit.sh:16]: Exactly! http://supervisord.org/running.html#signal-handlers

Comment (blms) [reply singularity/quit.sh:16]: Also, by sending this signal to the PID of this DPdash instance's `supervisord` (by grabbing it from `/data/dpdash/supervisord`), we ensure that any other running instance on the same machine will be untouched. Which also goes for all of its supervised processes.

Comment (tashrifbillah) [reply singularity/quit.sh:16]: Sure, thanks for devising this.

File: singularity/renewssl.sh [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+if [ ! -z ${DPDASH_SERVICE_HOST} ]
+then 
+    serviceHost=$DPDASH_SERVICE_HOST
+else
+    serviceHost=`hostname -f | xargs`
+fi
+cd ${containerDataDir}/ssl/ca
+
+echo 'Revoking existing certs'
+dirpath=${containerDataDir}/ssl/ca/certs
```
Comment (tashrifbillah) [inline singularity/renewssl.sh:22]: For the record, I am putting the directory hierarchy here so `cd`s are better understood
```
ssl/
├── ca
│   ├── cacert.pem
│   ├── certs
│   │   ├── 01.pem
│   │   └── 02.pem
│   └── private
│       └── cakey.pem
├── client
│   ├── cert.pem
│   ├── key.pem
│   └── req.pem
├── mongo_client.pem
├── mongo_server.pem
└── server
    ├── cert.pem
    ├── key.pem
    └── req.pem
```

Comment (blms) [reply singularity/renewssl.sh:22]: Sure. BTW,  all lines below 26 are identical to here:

https://github.com/PREDICT-DPACC/dpdash/blob/585cb7cba46c2b3cd72432975340d8133dde47d6/singularity/init.sh#L51-L79

File: singularity/renewssl.sh [hunk 5]
```diff
@@ -0,0 +1,54 @@
+#!/bin/bash
```
Comment (tashrifbillah) [inline singularity/renewssl.sh:1]: So when the certificates expire, should a user do:

```
./renewssl.sh
```

Comment (blms) [reply singularity/renewssl.sh:1]: Yes, and I made a wiki to hopefully help explain: https://github.com/PREDICT-DPACC/dpdash/wiki/Renewing-self-signed-SSL-certificates

Comment (blms) [reply singularity/renewssl.sh:1]: Actually, not `/sw/apps/dpdash/singularity`, because it must be done outside of the container (like `init.sh`).

**Review by tashrifbillah — APPROVED** [review]
Neat and important!
